[book]
title = "The Rulebook"
authors = ["Andrew Thomas Christensen"]
language = "en"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[rust]
edition = "2021"
