# SPDX-FileCopyrightText: 2024 Andrew T. Christensen <andrew@andrewtc.com>
#
# SPDX-License-Identifier: MIT

name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cargo-msrv
      run: cargo install cargo-msrv

    - name: Verify minimum supported Rust version
      run: cargo msrv --output-format json verify -- cargo check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Install cargo-deadlinks
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-deadlinks
        git: https://github.com/deadlinks/cargo-deadlinks

    - name: Run cargo deadlinks
      run: cargo deadlinks
